/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wcj1901010227;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VACation
 */
public class AdminUI extends javax.swing.JFrame {

    ClientUI parentUI;
    RegisterUI registerUI=null;
    InetAddress remoteAddress=null;
    ResultTableUI resultTableUI=null;
    int remotePort;
    DatagramSocket clientSocket;
    DatagramPacket packet;
    TeacherSignUpUI signupUI=null;
    SignUpTableUI signUpTableUI;
    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
    }
    public AdminUI(InetAddress remoteAddress,int remotePort,ClientUI parentUI)
    {
        this();
        
        this.remoteAddress=remoteAddress;
        this.remotePort=remotePort;
        
        this.parentUI=parentUI;
        try {
            this.clientSocket=new DatagramSocket();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"初始化失败",JOptionPane.ERROR_MESSAGE);
        }
        
    }

    //向服务器发送查询请求
    private Boolean SendMessage(String messageType)
    {
        boolean check=false;
        Message message=new Message();
        message.setType(messageType);
        try {
                
                clientSocket.setSoTimeout(3000);//设置超时时间
                message.setToAddr(remoteAddress);
                message.setToPort(remotePort);
                message.setIsAdmin(true);
                byte[] data=Translate.ObjectToByte(message);
                packet=new DatagramPacket(data, data.length,remoteAddress,remotePort);
                clientSocket.send(packet);
                check=true;
                //获取回送的消息
//                DatagramPacket backPacket=new DatagramPacket(data,data.length);
//                clientSocket.receive(backPacket);
//                clientSocket.setSoTimeout(0);
//                Message backMessage=(Message)Translate.ByteToObject(data);
//                if(backMessage.getType().equalsIgnoreCase("M_SUCCESS"))
//                {
//                    check=true;
//                }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"发送请求出错",JOptionPane.ERROR_MESSAGE);
            
        }
        return check;
    }
    private Message ReceiveMessage()
    {
        boolean check = false;
         Message backMessage=new Message();
        try {
            
            clientSocket.receive(packet);
            clientSocket.setSoTimeout(0);
            backMessage = (Message) Translate.ByteToObject(packet.getData());
            if (backMessage.getType().equalsIgnoreCase("M_SUCCESS")) {
                check = true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"接受消息出错",JOptionPane.ERROR_MESSAGE);
        }
        if(check)
        {
            return backMessage;
        }
        backMessage.setType("M_FAILURE");
        return backMessage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnQuery = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        ButtonPanel = new javax.swing.JPanel();
        btnSilence = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TopPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "班级管理面板", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 18))); // NOI18N

        btnAdd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnAdd.setText("添加学生信息");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnDel.setText("删除学生信息");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnQuery.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnQuery.setText("查询所有人信息");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        btnModify.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnModify.setText("修改学生信息");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDel)
                        .addGap(18, 18, 18)
                        .addComponent(btnModify))
                    .addGroup(TopPanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnQuery)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        ButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 18)), "课堂管理面板", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 18))); // NOI18N

        btnSilence.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnSilence.setText("全体禁言");
        btnSilence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilenceActionPerformed(evt);
            }
        });

        btnSignUp.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnSignUp.setText("发起签到");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnCheck.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnCheck.setText("查看签到结果");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSilence, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheck)
                .addGap(56, 56, 56))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSilence, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        registerUI=new RegisterUI(null,remoteAddress.getHostName(),remotePort);
        registerUI.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        // TODO add your handling code here:
        if(SendMessage("M_QUERY"))
        {
            if (ReceiveMessage().getType().equalsIgnoreCase("M_SUCCESS")) {
                resultTableUI = new ResultTableUI(btnQuery.getText(), this, parentUI.sqlHelper);
                DefaultTableModel tableModel = parentUI.sqlHelper.GenerateTableModel(btnQuery.getText());
                if (tableModel != null) {
                    resultTableUI.setTableModel(tableModel);
                }

                resultTableUI.setVisible(true);
            }

        }
        else
        {
            JOptionPane.showConfirmDialog(null, "服务器好像有点开小差...");
        }
        
        
        
        
    }//GEN-LAST:event_btnQueryActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        if(SendMessage("M_QUERY"))
        {
            if(ReceiveMessage().getType().equalsIgnoreCase("M_SUCCESS"))
            {
                resultTableUI = new ResultTableUI(btnDel.getText(), this, parentUI.sqlHelper);
                DefaultTableModel tableModel = parentUI.sqlHelper.GenerateTableModel(btnDel.getText());
                if (tableModel != null) {

                    resultTableUI.setTableModel(tableModel);
                }

                resultTableUI.setVisible(true);
            }
            
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "服务器好像有点开小差...");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
         if(SendMessage("M_QUERY"))
        {
            if(ReceiveMessage().getType().equalsIgnoreCase("M_SUCCESS"))
            {
                resultTableUI = new ResultTableUI(btnModify.getText(), this, parentUI.sqlHelper);
                DefaultTableModel tableModel = parentUI.sqlHelper.GenerateTableModel(btnModify.getText());
                if (tableModel != null) {

                    resultTableUI.setTableModel(tableModel);
                }

                resultTableUI.setVisible(true);
            }
            
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "服务器好像有点开小差...");
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnSilenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilenceActionPerformed
        // TODO add your handling code here:
        if(btnSilence.getText().equals("全体禁言"))
        {
            
            if (SendMessage("M_Silence")) {
                if(ReceiveMessage().getType().equalsIgnoreCase("M_SUCCESS"))
                {
                    btnSilence.setText("解除全体禁言");
                    parentUI.txtArea.append("您发起了全体禁言...\n");
                }
                
            }
        }
        else if(btnSilence.getText().equals("解除全体禁言"))
        {
            if(SendMessage("M_Speak"))
            {
                if(ReceiveMessage().getType().equalsIgnoreCase("M_SUCCESS"))
                {
                    btnSilence.setText("全体禁言");
                    parentUI.txtArea.append("您取消了全体禁言...\n");
                }
                
            }
        }
    }//GEN-LAST:event_btnSilenceActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        if(SendMessage("M_READY"))
        {
            Message backMessage;
            if((backMessage=ReceiveMessage()).getType().equalsIgnoreCase("M_SUCCESS"))
            {
                if(signupUI==null)
                {
                    int onlineNumber=Integer.parseInt(backMessage.getText());
                    signupUI=new TeacherSignUpUI(onlineNumber,0,this);
                    signupUI.setVisible(true);
                    
                }
                
            }
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        
        if(SendMessage("M_QUERY"))
        {
            if(ReceiveMessage().getType().equalsIgnoreCase("M_SUCCESS"))
            {
                int tablenumber = parentUI.sqlHelper.GetSignUpTableNumber();
                if (tablenumber == 0) {
                    JOptionPane.showConfirmDialog(null, "您至少需要有一条签到记录才能查看...");
                    return;
                }
                signUpTableUI = new SignUpTableUI(this, parentUI.sqlHelper);
                signUpTableUI.showTable();
                
                
                
                
            }
            
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "服务器好像有点开小差...");
        }
        
        
    }//GEN-LAST:event_btnCheckActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnSilence;
    // End of variables declaration//GEN-END:variables
}
