/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wcj1901010227;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author VACation
 */
public class SignUpTableUI extends javax.swing.JFrame {

    /**
     * Creates new form SignUpTableUI
     */
    AdminUI parentUI;
    SqlHelper sqlHelper=null;
    public SignUpTableUI() {
        initComponents();
    }
    public SignUpTableUI(AdminUI parentUI,SqlHelper sqlHelper)
    {
        this();
        this.parentUI=parentUI;
        this.sqlHelper=sqlHelper;
        ArrayList<String> tableList=sqlHelper.GetSignupTableName();
        if(tableList!=null)
        {
            boxTableNemes.removeAllItems();
            for(int i=0;i<tableList.size();i++)
            {
                boxTableNemes.addItem(tableList.get(i));
            }
            boxTableNemes.setSelectedIndex(tableList.size()-1);//总是选中并展示最新表
            
            
        }
        
    }
    private void setTableModel(DefaultTableModel tableModel)
    {
        ResultTable.setModel(tableModel);
        JTableHeader header=ResultTable.getTableHeader();
        header.setFont(new Font("微软雅黑", Font.PLAIN, 20));
        
        
    }
    public void showTable()
    {
        DefaultTableModel tableModel=sqlHelper.GenerateSignUpTableModel(boxTableNemes.getSelectedItem().toString());
        setTableModel(tableModel);
        
        TableColumnModel columnModel=ResultTable.getColumnModel();
        
        
        ResultTable.getColumnModel().getColumn(0).setPreferredWidth(80);

        ResultTable.getColumnModel().getColumn(1).setPreferredWidth(100);

        ResultTable.getColumnModel().getColumn(2).setPreferredWidth(100);

        ResultTable.getColumnModel().getColumn(3).setPreferredWidth(60);
        ResultTable.getColumnModel().getColumn(4).setPreferredWidth(180);
        ResultTable.setColumnModel(columnModel);
        
        this.setVisible(true);
        
    }
        private void ExecuteModify()
    {
        int response=JOptionPane.showConfirmDialog(null, "按确定更新信息", "更新信息", 2);
        if (response == 0) {
            boolean check = false;
            DefaultTableModel tableModel = (DefaultTableModel) ResultTable.getModel();
            Vector<Vector> dataVector = tableModel.getDataVector();
            Iterator iterator = dataVector.iterator();
            while (iterator.hasNext()) {
                Vector<Object> temp = (Vector<Object>) iterator.next();
               
                String account = (String) temp.get(1);
                
                
                boolean state = (boolean) temp.get(3);
                int stateNumber = 0;
                if (state == true) {
                    stateNumber = 1;
                } else {
                    stateNumber = 0;
                }
                

                check = sqlHelper.UpdateSign(boxTableNemes.getSelectedItem().toString(),account, stateNumber);
                if (!check) {
                    JOptionPane.showMessageDialog(null, "更新数据异常");
                }
            }
            ResultTable.updateUI();
        }

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ResultTable = new javax.swing.JTable();
        boxTableNemes = new javax.swing.JComboBox<>();
        btnFresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("签到结果");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "签到表", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 18))); // NOI18N

        ResultTable.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        ResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ResultTable.setPreferredSize(new java.awt.Dimension(300, 160));
        ResultTable.setRowHeight(30);
        jScrollPane1.setViewportView(ResultTable);

        boxTableNemes.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        boxTableNemes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFresh.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnFresh.setText("查看此表格");
        btnFresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFreshActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 51, 51));
        btnSave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnSave.setText("保存修改");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnClose.setText("返回");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxTableNemes, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnFresh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTableNemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        parentUI.signUpTableUI=null;
    }//GEN-LAST:event_formWindowClosed

    private void btnFreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFreshActionPerformed
        // TODO add your handling code here:
        showTable();
        ResultTable.updateUI();
    }//GEN-LAST:event_btnFreshActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ExecuteModify();
        showTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpTableUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpTableUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpTableUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpTableUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpTableUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ResultTable;
    private javax.swing.JComboBox<String> boxTableNemes;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
